### PR TITLE
mend the mistake at line 205

### PR DESCRIPTION
**Pull request by memenpu**
thanks

### CODE REVIEW

**Comment by Hassan-Shabbir** [comment]
Actually, both `o` and `O` are incorrect in the file. They have been changed now.

**Comment by Hassan-Shabbir** [comment]
Also, thanks for the pull request. I thought making people go through that process would be too difficult.

**Comment by Hassan-Shabbir** [comment]
Oh, and you're welcome! (Referring to your thanks in the original comment.)

**Comment by Hassan-Shabbir** [comment]
Oh, and I can't believe that you modified the correct file as well. 

And somewhat related, did you modify the file using github, or did you clone the repository, modify the file, commit the change, then create a pull request using the terminal?

**Comment by memenpu** [comment]
I did that on the website. Lol

**Comment by Hassan-Shabbir** [comment]
Oh, alright. If you want I can teach you how to do it the way I described above. Fair warning though, I am quite new to this process as well.

**Pull request closed without merging**
